name: Build and Deploy to Prod
on: workflow_dispatch
jobs:
  buildDeployProd:
    uses: ./.github/workflows/build-deploy.yml
    secrets:
      NPM: ${{ secrets.NPM }}
      GH_PAT: ${{ secrets.GH_PAT }}
    with:
      awk: sed "s/-.*//g" | awk -F. '{print $1"."$2"."$3+1}'
      rails: '[[ ! "$VERSION" =~ "rc" ]] && [[ ! "$VERSION" =~ "pre" ]]'
