name: Build and Deploy to Sandbox
on:
  pull_request:
    types: [closed]
    branches:
    - 'v?[0-9]+.[0-9]+'
jobs:
  buildDeploySandbox:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build-deploy.yml
    secrets:
      NPM: ${{ secrets.NPM }}
      GH_PAT: ${{ secrets.GH_PAT }}
    with:
      awk: sed -e "s/pre/rc/g" | awk -F. '{print $1"."$2"."$3"."$4+1}'
      rails: '[[ ! "$VERSION" =~ "pre" ]]'

